

name = "csedd-dataworker"
type = "worker"
binding = "dataWorker"
service = "csedd-dataworker"
script = "dataworker.js"
main = "src/index.ts"
account_id = "672d2bf9aea3df86bf6cc201c11327c1"
workers_dev = true
compatibility_date = "2024-11-01"

services = [
    {binding = "dataWorker", service = "csedd-dataworker" }
]

[build]
upload.format = "modules"

[[d1_databases]]
binding = "DB"
database_name = "csedd-datastore"
database_id = "bcfa7c7a-ef7f-48e3-95ad-cbb73a71eafe"
compatibility_date = "2024-11-01"
