
[[services]]
binding = "dataWorker"
service = "csedd-dataworker"
script = "index"
type = "worker"
main = "src/index.ts"
workers_dev = false
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "csedd-datastore"
database_id = "bcfa7c7a-ef7f-48e3-95ad-cbb73a71eafe"
compatibility_date = "2024-11-01"
