

name = "csedd-dataworker"
type = "javascript"
account_id = "672d2bf9aea3df86bf6cc201c11327c1"
workers_dev = true
compatibility_date = "2024-11-01"

[build]
upload.format = "modules"

[[services]]
binding = "dataWorker"
service = "csedd-dataworker"
script = "ui"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "csedd-datastore"
database_id = "bcfa7c7a-ef7f-48e3-95ad-cbb73a71eafe"
compatibility_date = "2024-11-01"
